# Site settings
title: Cordwainer
email: iamkcerb@gmail.com
description: Cordwainer is a home for tutorials about how Shoes works deep deep down.
baseurl: '/cordwainer'
url: "http://yourdomain.com" # the base hostname & protocol for your site
github_username:  kcerb

# Build settings
markdown: redcarpet
